version: '3'
services:
  yuri_teste:
    container_name: yuri_teste
    hostname: yuri_teste_host
    build:
      dockerfile: .docker/Dockerfile
      context: ./
    ports:
      - 8080:80
    volumes:
      - ./htdocs:/var/www/html/
    restart: unless-stopped